export const rowCards = document.querySelector("#rowCards");
export const formData = document.querySelector("#formData");
export const NameSearch = document.querySelector("#name");
export const spinner = document.querySelector("#Spinner");
export const error = document.querySelector("#error");
export const generateCharacterCard = (character) => {
    var _a;
    const cardCol = document.createElement('div');
    const cardDiv = document.createElement('div');
    const cardRow = document.createElement('div');
    const cardColImage = document.createElement('div');
    const cardImage = document.createElement('img');
    const cardColCharacter = document.createElement('div');
    const cardCharacterBody = document.createElement('div');
    const cardCharacterTitle = document.createElement('h5');
    const cardCharacterEpisodes = document.createElement('p');
    const cardCharacterEpisodesText = document.createElement('small');
    const cardCharacterDivHref = document.createElement('div');
    const cardCharacterLink = document.createElement('a');
    cardCol.classList.add("col-4");
    cardDiv.classList.add("card", "mb-3", "mt-5");
    cardDiv.setAttribute("style", "max-width: 540px");
    cardRow.classList.add("row", "g-0");
    cardColImage.classList.add("col-md-4");
    cardImage.classList.add("img-fluid", "rounded-start");
    cardImage.setAttribute("src", character.image);
    cardColCharacter.classList.add("col-md-8");
    cardCharacterBody.classList.add("card-body");
    cardCharacterTitle.textContent = character.name;
    cardCharacterEpisodesText.classList.add("text-muted");
    cardCharacterEpisodesText.textContent = "ha aparecido en " + ((_a = character.episode) === null || _a === void 0 ? void 0 : _a.length) + " episodios";
    cardCharacterDivHref.classList.add("text-start", "mt-3");
    cardCharacterLink.classList.add("btn", "btn-primary");
    cardCharacterLink.setAttribute("href", `./personaje.html?id=${character.id}`);
    cardCharacterLink.textContent = "Ver personaje";
    cardCharacterEpisodes.append(cardCharacterEpisodesText);
    cardCharacterDivHref.append(cardCharacterLink);
    cardCharacterBody.append(cardCharacterTitle, cardCharacterEpisodesText, cardCharacterDivHref);
    cardColCharacter.append(cardCharacterBody);
    cardColImage.append(cardImage);
    cardRow.append(cardColImage, cardColCharacter);
    cardDiv.append(cardRow);
    cardCol.append(cardDiv);
    return cardCol;
};
